name: skip

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: no-runners-match-this
    steps:
      - name: hello
        run: echo "hello"
      - name: never
        if: false
        run: echo "never"
      - name: goodbye
        run: echo "goodbye"
